# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/mdouchement/workerpool
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: gometalinter --config=gometalinter.json ./...
      - run: go test -race -v
